#!/usr/bin/env python3

import sleekxmpp
import logging
import interpreter


class BestBot(sleekxmpp.ClientXMPP):
    def __init__(self, jid, password):
        super(BestBot, self).__init__(jid, password)        
        self.add_event_handler("session_start", self.session_start)
        self.add_event_handler("got_online", self.got_online, threaded=True)

    def session_start(self, event):
        self.send_presence()
        self.get_roster()

    def got_online(self, event):
        qq = interpreter.Interpreter(self)
        while not self.stop.is_set():
            qq.load()


if __name__ == '__main__':
    
    logging.basicConfig(level=logging.DEBUG,
                        format='%(levelname)-8s %(message)s')

    xmpp = BestBot('matheus@localhost/Probe1.0', 'matheus')
    xmpp.connect()
    xmpp.process(block=True)
