#!/usr/bin/env python3

import sleekxmpp
import logging
import colorlog

import interpreter


class BestBot(sleekxmpp.ClientXMPP):
    def __init__(self, jid, password):
        super().__init__(jid, password)        
        self.add_event_handler("session_start", self.session_start)
        self.add_event_handler("got_online", self.got_online, threaded=True)

    def session_start(self, event):
        self.send_presence()
        self.get_roster()

    def got_online(self, event):
        qq = interpreter.Interpreter(self)
        while not self.stop.is_set():
            qq.load()


if __name__ == '__main__':
    
    logging.getLogger().setLevel('INFO')

    console = logging.StreamHandler()
    color_fmt = colorlog.ColoredFormatter('%(asctime)s %(log_color)s'
                                          '%(levelname)s\t%(message)s')
    console.setFormatter(color_fmt)
    logging.getLogger().addHandler(console) 
    

    xmpp = BestBot('simon@xmpp.algartelecom.com.br/Simon', 'simon')
    xmpp.connect()
    xmpp.process(block=True)
